Reduced GCP SA permission scope
truefoundry/terraform-google-truefoundry-platform-features pull request #5
Opened 2024-05-08 15:52 UTC by DeeAjayi

2024-05-09 13:10 UTC, dunefro requested changes

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +    expression  = "resource.name.startsWith('projects/_/buckets/tfy')"
```suggestion
    expression  = "resource.name.startsWith('projects/_/buckets/${module.blob_storage[0].name}')"
```

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +// add service account to token creator role
Please change the comment respectively

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +// add artifact registry role to service account
Please change the comment respectively

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +// add container cluster viewer role to service account
Please change the comment respectively

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +// add container viewer role to service account
Please change the comment respectively

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +// service account key
Please change the comment respectively

2024-05-09 13:10 UTC, dunefro commented on iam.tf
> +resource "google_project_iam_member" "token_creator_role_binding" {
Change the terraform resource name accordingly

2024-05-09 13:30 UTC, DeeAjayi commented on iam.tf
> +  role_id     = replace("${local.trufoundry_platform_resources}_bucket_secret_manager_tfy_role", "-", "_")
hyphens are not accepted

2024-05-09 13:33 UTC, DeeAjayi commented on iam.tf
> +  role_id     = replace("${local.trufoundry_platform_resources}_bucket_gcs_tfy_role", "-", "_")
no we can't 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role#role_id

2024-05-10 08:36 UTC, dunefro approved these changes
LGTM

2024-05-10 08:39 UTC, merged